### ISSUE TITLE
Clear MacOS Terminal badge

### ISSUE THREAD

**Issue by simonkuran** [sindresorhus/beeper#15]
Is it possible to clear the red "1" badge on MacOS's Terminal app when my build has been successful? Often I instantly know why I made a syntax error and it would be nice to not have to actively go into the Terminal app to clear the badge when I don't have to.

**Comment by sindresorhus** [comment]
I don't think there's any way to do that programmatically. You could disable the badge altogether though: https://osxdaily.com/2013/04/29/disable-red-badge-app-icons-mac-os-x/

**Comment by simonkuran** [comment]
Thanks for confirming.
