### ISSUE TITLE
BELL doesn't work in cmd

### ISSUE THREAD

**Issue by Richienb** [sindresorhus/beeper#16]
From my experience, the BELL character doesn't really work in cmd. An alternative is to execute `rundll32 user32.dll,MessageBeep` to do the same thing.

**Comment by sindresorhus** [comment]
Pretty much nothing works in `cmd`. I would recommend using https://github.com/microsoft/terminal instead. If `BELL` doesn't work there, open an issue there, and it will probably be fixed there at some point. I'm not interested in adding a workaround. Lately, I've spent way too much time adding/reviewing Windows workarounds.
