### ISSUE TITLE
No callback after beeps have finished

### ISSUE THREAD

**Issue by prettycode** [sindresorhus/beeper#3]
I use beeper before I call `process.exit()`.

Because of beeper's `setTimeout()`s, if I `require('beeper')(5); process.exit();` I only hear one beep. This is on Windows, by the way.

If beeper checked for the last element in `arguments` being a function and treated that like a callback, I could do this, and hear 5 beeps:

    require('beeper')(5, function() {
        process.exit();
    });

Alternatively, beeper could return a promise so I could instead do:

    `require('beeper')(5).then(process.exit);`

I can submit a PR if this idea is tenable.

**Comment by prettycode** [comment]
Here's the workaround I'm using:

    var q = require('q');
    var _ = require('lodash');
    var beeper = require('beeper');

    function beep(count) {
        return q.all(_.times(count, function (n) {
            return q.delay(undefined, n * 500).then(beeper);
        }));
    }

    beep(3).done(process.exit);

**Comment by sindresorhus** [comment]
Sure, a callback sounds fine.

**Comment by sindresorhus** [comment]
Still interested in doing a PR? :)
